### PR TITLE
Add Centos 6 support and  fix root user requirement

### PR DESCRIPTION
**Pull request by zoonage**
Fixes the requirement to run as the root user to preserve file permissions from https://github.com/lest/prometheus-rpm/issues/36. This is done by noting the uid and gid of the files before changing them in the container (which makes them owned by root) and then reverts them back when the container ends. If the container fails then the permissions are not changed.

Adds support for building RPMs for centos 6.

### CODE REVIEW

**Comment by britcey** [comment]
@lest can you merge this and republish the image?  That way we can clean up the Makefile for lest/prometheus-rpm a bit.

**Comment by zoonage** [comment]
This could also do with an extension to support centos 8 for https://github.com/lest/prometheus-rpm/issues/152, I don't really work with centos based distros any more so I'm not keeping up to date with them.

It would also be good to change https://github.com/lest/prometheus-rpm/blob/master/Makefile#L53 back to images under @lest control for future maintainability as opposed to the images I pushed to quay.io

**Comment by britcey** [comment]
"It would also be good to change https://github.com/lest/prometheus-rpm/blob/master/Makefile#L53 back to images under @lest control for future maintainability as opposed to the images I pushed to quay.io"

My thinking exactly.

**Comment by lest** [comment]
The pull request seems to contain various changes. Are main changes supporting CentOS 6 and installing yum-utils? Am I missing some other important changes?

**Comment by britcey** [comment]
I think the build-spec permissions changes are also notable.  I _think_ that's the key bit for the couchbase_exporter PR.

Looking more closely, I think you'd probably want to s/zoonage/lest/ in all the files, assuming we want to keep everything consistent and under your name.

**Comment by zoonage** [comment]
I've removed my own username and put @lest 's back in, good spot

**Comment by zoonage** [comment]
@lest any update on this? I've just had someone try and push https://github.com/zoonage/centos-rpm-builder-docker/pull/4 over to me, but it looks like you've already done this on your side

**Comment by lest** [comment]
@zoonage yes, I've created CentOS 6 and CentOS 8 images for building RPM packages.

Your pull request contains tests that I'd like to see added to the repository. I plan on adding them to the repository. I would appreciate if you could update the pull request to run tests on all three images.

**Pull request closed without merging**
